# A sample Gemfile
source :gemcutter

gem "rails", "2.3.10"
gem "devise", "1.0.8"
gem "haml", "3.0.18"
gem "pg", "0.9.0"
#gem "tiny_mce", "0.1.3"
gem "formtastic", "1.0.1"
gem "delayed_job", "2.0.3"
gem "param_protected", "1.3.0"
gem "attribute_normalizer", "0.3.1"
gem "methodchain", "0.4.2"
gem "validation_reflection", "0.3.8"
#gem "validatious-on-rails"#, :git => "http://github.com/grimen/validatious-on-rails.git"
#gem "coffee-haml-filter", "0.4.0"
#gem "bistro_car", "0.2.2"
gem "searchlogic", "2.4.25"
gem "cancan", "1.3.4"
gem "devise_invitable", "0.2.3"